export interface ICareer {
  title: string;
  qualifications: string[]; // Array of qualifications as strings
  placeName: string;
  createdAt?: string; // Optional timestamp, auto-generated by Mongoose
  updatedAt?: string;
  _id: string;
}
